### ISSUE TITLE
Round not found

### ISSUE THREAD

**Issue by WilliamDASILVA** [Hartorn/ffs-zera#30]
Getting the 'Round not found' error

Steps to reproduce:
- From the homepage, go to 'Liste des evenements' then select an event.
- After that, click on 'Evenements en direct' and none of the rounds tabs is selected by default. Causes the 'Round not found' error.

Private mode, Firefox Quantum 57.0, Windows.

**Comment by Hartorn** [comment]
Okay, problem is due to store still having data from the event page, so it cause a problem here
https://github.com/Hartorn/ffs-zera/blob/master/app/views/events/detail/round-list-view.js#L42

Will fix this on Friday, or this week end
